name: Build

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    build:
        name: build
        runs-on: macOS-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            submodules: true

        - name: Check XCode Version
          run: |
            xcversion select 12.3
            xcodebuild -version

        - name: Test
          run: |
            set -o pipefail && xcodebuild clean test -project School42Header.xcodeproj -scheme School42Header CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
